### PR TITLE
Editorial changes

### PR DESCRIPTION
**Pull request by paulehoffman**
Hyphenation fixes, remove some dangling text.

### CODE REVIEW

**Comment by dstebila** [comment]
The punctuation in Diffie–Hellman is an en-dash, not a hyphen, but there's no en-dash in low ASCII.  Does IETF have a fixed convention on how en-dashes should be represented in low ASCII?

**Comment by paulehoffman** [comment]
Why do you feel that the "punctuation in Diffie–Hellman is an en-dash"? I have never seen that in any professional style guide. My Chicago Manual of Style (15th Ed, a tad old) definitely disagrees with you in rules 6.81 and 6.83.

**Comment by dstebila** [comment]
https://en.wikipedia.org/wiki/Dash#Relationships_and_connections

**Comment by paulehoffman** [comment]
I'll defer to the CMOS (and the AP Style Guide) over Wikipedia on this one. I also note that the RFC Editor does use en-dashes, but only for the things listed in CMOS and AP: ranges of dates and pages. The RFC Editor consistently uses a hyphen in all the RFCs that mention Diffie-Hellman.

**Comment by dstebila** [comment]
That CMOS and AP Style Guide prefer hyphens is not enough to make me change, since there is an acknowledged diversity of opinion among style guides on this matter. But if RFC Editor consistently uses hyphens for Diffie-Hellman, I'll defer to their choice for consistency.

**Review by dstebila — APPROVED** [review]

**Pull request merged**
